services:
    app.command.test_reset_data:
        class: BOF\Command\TestDataResetCommand
        tags:
            - { name: console.command }

    app.command.report_yearly:
        class: BOF\Command\ReportYearlyCommand
        tags:
            - { name: console.command }

    app.command.cron_generate_stastics:
            class: BOF\Command\CronGenerateStatisticsCommand
            tags:
                - { name: console.command }