services:

    app.command.test_reset_data:
        class: BOF\Command\TestDataResetCommand
        tags:
            - { name: console.command }

    app.command.report_yearly:
        class: BOF\Command\ReportYearlyCommand
        arguments: ['@app.repository.profile', '@app.utils.profiledatahelper']
        tags:
            - { name: console.command }

    app.repository.profile:
        class: BOF\Repository\Profile
        arguments: ['@database_connection']

    app.utils.profiledatahelper:
        class: BOF\Utils\ProfileDataHelper